feat(ui): implement my event page
NJUPT-SAST/sast-evento pull request #22
Opened 2024-08-13 08:33 UTC by zwow-cj

![屏幕截图 2024-08-13 154703](https://github.com/user-attachments/assets/1c86a212-87c6-45de-a7ce-d98e91bbf4c0)
![屏幕截图 2024-08-13 154556](https://github.com/user-attachments/assets/fe6cbb0e-5851-47f7-bc2c-0a0dc1113e25)

2024-08-13 10:29 UTC, Serein207 commented
考虑使用 `STab` 组件分割每种日程：https://surrealism-all.github.io/SurrealismUI.github.io/components/nav/tab.html

全部状态有四个，分别是已报名 进行中 已结束 已取消

2024-08-13 10:45 UTC, cEvolve05 commented
不用在layout中表明每一个活动卡片的位置，你大可以写一个包含标题栏和一个VerticalLayout组件，然后在页面上放三个，这样后面也可以直接用for重复组件，另外分离布局和部件不是必须的，你可以分离，也可以合并。
另外figma中的这个页面我重写过一次，你应该是可以直接看到相应布局的。
对于这三个部分，是这样划分的：左右各半，右边上下各半。
同时已结束部分不作为主要内容，主要为了导航到历史活动。

2024-08-13 10:51 UTC, Serein207 commented
> 不用在layout中表明每一个活动卡片的位置，你大可以写一个包含标题栏和一个VerticalLayout组件，然后在页面上放三个，这样后面也可以直接用for重复组件，另外分离布局和部件不是必须的，你可以分离，也可以合并。
> 
> 另外figma中的这个页面我重写过一次，你应该是可以直接看到相应布局的。对于这三个部分，是这样划分的：左右各半，右边上下各半。
> 
> 同时已结束部分不作为主要内容，主要为了导航到历史活动。

状态是已取消的活动放在什么地方，和已报名的混在一起，再盖一层蒙版吗

2024-08-13 11:09 UTC, cEvolve05 commented
@zwow-cj 已取消的活动可以单独一个组件放在左侧的底部，或者放在右侧挤一挤，具体由你安排。

在近期没有取消的活动时可以不显示，只作为一个提醒；或者你也可以放在原处，但是用特别的样式提醒用户活动已取消；或者用其他的方式提醒用户活动已经取消，同时不破坏整体的布局。

2024-08-19 13:52 UTC, zwow-cj commented
签到和评价按钮ui样式已写好，并且评价按钮可以跳转到历史页面。
  本次提交了页面模板，没有加入已取消活动。对此有疑问，已取消活动需要单独写一个页面吗？通过链接或者按钮跳转？
  活动详情的更新是否是我完成还是只提供页面模板？

2024-08-19 13:58 UTC, zwow-cj commented
关于界面滚动条我是否需要加入？曾尝试在page里加上scrollview但是编译报错

2024-08-19 15:08 UTC, Serein207 commented
>   关于界面滚动条我是否需要加入？曾尝试在page里加上scrollview但是编译报错

应该给每个分类的活动时间轴单独加滚动条，而不是套在整个页面上

2024-08-19 15:11 UTC, Serein207 commented
>   签到和评价按钮ui样式已写好，并且评价按钮可以跳转到历史页面。

点击 评价 应该跳转到活动详情页

点击 查看更多 跳转到历史活动页

点击 签到 弹窗在文本框输入code签到

>   本次提交了页面模板，没有加入已取消活动。对此有疑问，已取消活动需要单独写一个页面吗？通过链接或者按钮跳转？

已取消的活动和未开始的活动混在一起，用特别的色块表示已取消

>   活动详情的更新是否是我完成还是只提供页面模板？

任务包括本页面所有的逻辑处理，网络请求和数据更新

2024-08-30 11:53 UTC, zwow-cj commented
scrollview暂时没加，基本内容写好了。有问题请指出。
构建时有个error，如下:
![屏幕截图 2024-08-30 194427](https://github.com/user-attachments/assets/74845da2-0771-431e-a0b5-a8c8994ad0c9)

2024-09-23 04:42 UTC, ArcticLampyrid requested changes

2024-09-23 04:42 UTC, ArcticLampyrid commented on ui/views/page/my_event.slint
> +        x: (parent.x)+40px;
Please use relative layout utilities eg. `HorizontalLayout` `VerticalLayout` `GridLayout` `PathLayout`, if possible.

2024-09-23 04:42 UTC, ArcticLampyrid commented on src/Controller/View/MyEventPage.cc
> +    self->on_show_mess([this](slint::SharedString part) { get_events(part); });
It's really a "mess". 😢😢
Can we just split it?

2024-09-23 04:42 UTC, ArcticLampyrid commented on src/Controller/View/MyEventPage.cc
> +    self->on_get_code([this](slint::SharedString code, int id) { return check_code(code, id); });
So why we use `get_code` on one side (Slint), but `check_code` on the other?

2024-09-25 13:50 UTC, Mairon1206 commented
并提供签到、取消报名按钮，评价可以跳转到详细页面或者历史活动页面

2024-09-25 13:50 UTC, closed without merging